Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
 config.vm.define "server1" do |server1|
   server1.vm.box = "geerlingguy/centos7"
   server1.vm.network "private_network", ip: "192.168.2.51" 
   server1.vm.hostname = "server1.innovyt.com" 
   server1.vm.provision "shell", path: "install_primary.sh" 
   server1.vm.network "forwarded_port", guest: 8080, host: 8080
   server1.vm.provider "virtualbox" do |v|
      v.memory = 1000
		v.name= "server1.innovyt.com"
		v.cpus= 1
 	v.customize ['modifyvm', :id, '--cableconnected1', 'on']
     end
   end
 config.vm.define "server2" do |server2|
   server2.vm.box = "geerlingguy/centos7"
   server2.vm.network "private_network", ip: "192.168.2.52" 
   server2.vm.hostname = "server2.innovyt.com" 
   server2.vm.provision "shell", path: "install_client.sh" 
   server2.vm.provider "virtualbox" do |v|
      v.memory = 1000
		v.name= "server2.innovyt.com"
		v.cpus= 1
 	v.customize ['modifyvm', :id, '--cableconnected1', 'on']
     end
   end
 config.vm.define "server3" do |server3|
   server3.vm.box = "geerlingguy/centos7"
   server3.vm.network "private_network", ip: "192.168.2.53" 
   server3.vm.hostname = "server3.innovyt.com" 
   server3.vm.provision "shell", path: "install_client.sh" 
   server3.vm.provider "virtualbox" do |v|
      v.memory = 1000
		v.name= "server3.innovyt.com"
		v.cpus= 1
 	v.customize ['modifyvm', :id, '--cableconnected1', 'on']
     end
   end
end
